name: ci

on: [push, pull_request]

jobs:
  build:
    name: Lit App ${{ matrix.kind }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macOS-latest]
        node-version: [15.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm i

      - run: npm run build

      - name: Format
        run: npm run lint

      - name: Tests
        run: npm run test